### PR TITLE
Add flake8 and fix errors

### PR DESCRIPTION
**Pull request by beanqueen**

### CODE REVIEW

**Comment by beanqueen** [comment]
WIP

**Comment by cyprieng** [comment]
Thanks! Can you just fix the 5 small issues on Quantified Code ?

**Comment by beanqueen** [comment]
hi, would you be ok to disable the string interpolation check? http://docs.quantifiedcode.com/configuration/config_disable_checks.html
as you can see in my last commit, i fixed all other warnings and left only that one. i think it's way better readable this way :)

**Comment by cyprieng** [comment]
Hum, i find format better than string interpolation, but I may be the only one...
Any thoughts on this @flavianh ?

**Comment by beanqueen** [comment]
@cyprieng I changed the code since flavianh didnt reply and you didnt merge it

**Comment by cyprieng** [comment]
Thanks!

**Pull request merged**
